# ./serverless.yml
service: opengento-on-fly-3d-generator

plugins:
  - serverless-esbuild # used for compiling/packaging the Typescript code
  - serverless-offline # used for local execution

provider:
  name: aws
  runtime: nodejs18.x

custom:
  meshy:
    apiKey: msy_1OpWrYbiyZUvRbdumXwwIENIOahevTOq6qYj

functions:
  # Serverless Framework specific syntax
  sendImage:
    handler: handler.sendImage
    events:
      - httpApi:
          path: /api/sendImage
          method: POST
    environment:
      API_KEY: ${self:custom.meshy.apiKey}

  getImage:
    handler: handler.getImage
    events:
      - httpApi:
          path: /api/getImage
          method: GET
    environment:
      API_KEY: ${self:custom.meshy.apiKey}
