# ./serverless.yml
useDotenv: true
service: opengento-on-fly-3d-generator

plugins:
  - serverless-esbuild # used for compiling/packaging the Typescript code
  - serverless-offline # used for local execution

provider:
  name: aws
  runtime: nodejs18.x

functions:
  # Serverless Framework specific syntax
  sendImage:
    handler: handler.sendImage
    events:
      - httpApi:
          path: /api/sendImage
          method: POST
    environment:
      API_KEY: ${env:MESHY_API_KEY}

  getImage:
    handler: handler.getImage
    events:
      - httpApi:
          path: /api/getImage
          method: GET
    environment:
      API_KEY: ${env:MESHY_API_KEY}
